version: "3.9"

services:
  app:
    build: .
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    restart: unless-stopped
    ports:
      - ${WEB_PORT}:${WEB_PORT}
